=== esle-elkartea/lankidetza00016/src/Fuentes y JavaDoc/aon-common/src/com/code/aon/common/bean/bean-config.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT bean-config (bean+)>
<!ELEMENT bean (pojo,dao?,listeners?,vetoListeners?)>
<!ELEMENT pojo (#PCDATA)>
<!ELEMENT dao (dao-factory,dao-method)>
<!ELEMENT dao-factory (#PCDATA)>
<!ELEMENT dao-method (#PCDATA)>
<!ELEMENT listeners (listener+)>
<!ELEMENT listener (#PCDATA)>
<!ELEMENT vetoListeners (vetoListener+)>
<!ELEMENT vetoListener (#PCDATA)>

<!ATTLIST bean-config xmlns CDATA #FIXED ''>
<!ATTLIST bean xmlns CDATA #FIXED ''
  description CDATA #REQUIRED>
<!ATTLIST bean xmlns CDATA #FIXED ''>
<!ATTLIST pojo xmlns CDATA #FIXED ''>
<!ATTLIST dao xmlns CDATA #FIXED ''>
<!ATTLIST dao-factory xmlns CDATA #FIXED ''>
<!ATTLIST dao-method xmlns CDATA #FIXED ''>
<!ATTLIST listeners xmlns CDATA #FIXED ''>
<!ATTLIST listener xmlns CDATA #FIXED ''>
<!ATTLIST vetoListeners xmlns CDATA #FIXED ''>
<!ATTLIST vetoListener xmlns CDATA #FIXED ''>

=== esle-elkartea/lankidetza00016/src/Fuentes y JavaDoc/aon-gtm/WebRoot/WEB-INF/conf/bean_config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bean-config 
	PUBLIC "-//CODE-AON//DTD Bean Config//EN" 
	"http://co-de.com/aon/bean-config.dtd">

<bean-config>
	
	<bean description="">
		<pojo>com.code.aon.finance.InvoiceDetail</pojo>
		<listeners>
	        <listener>com.code.aon.finance.event.InvoiceDetailBeanListener</listener>
		</listeners>
		<vetoListeners>
	        <vetoListener>com.code.aon.finance.event.InvoiceDetailBeanVetoListener</vetoListener>
		</vetoListeners>
	</bean>

	<bean description="">
		<pojo>com.code.aon.product.Item</pojo>
		<listeners>
	        <listener>com.code.aon.ui.product.event.ItemListener</listener>
		</listeners>
	</bean>
	
	<bean description="">
		<pojo>com.code.aon.finance.Invoice</pojo>
		<listeners>
	        <listener>com.code.aon.finance.event.InvoiceBeanListener</listener>
		</listeners>
	</bean>
	
	<bean description="Listener para controlar el stock al haber movientos en albaranes de compra">
		<pojo>com.code.aon.warehouse.IncomeDetail</pojo>
		<listeners>
	        <listener>com.code.aon.warehouse.event.StockableBeanListener</listener>
		</listeners>
		<vetoListeners>
	        <vetoListener>com.code.aon.warehouse.event.StockableBeanVetoListener</vetoListener>
		</vetoListeners>
	</bean>
	
	<bean description="Listener para controlar el stock al haber movientos en albaranes de venta">
		<pojo>com.code.aon.warehouse.DeliveryDetail</pojo>
		<listeners>
	        <listener>com.code.aon.warehouse.event.StockableBeanListener</listener>
		</listeners>
		<vetoListeners>
	        <vetoListener>com.code.aon.warehouse.event.StockableBeanVetoListener</vetoListener>
		</vetoListeners>
	</bean>

	<bean description="">
		<pojo>com.code.aon.tas.TasItem</pojo>
		<vetoListeners>
	        <vetoListener>com.code.aon.ui.tas.event.TasItemBeanVetoListener</vetoListener>
		</vetoListeners>
	</bean>
	
	<bean description="">
		<pojo>com.code.aon.account.AccountEntryDetail</pojo>
		<listeners>
	        <listener>com.code.aon.account.event.AccountSummaryBeanListener</listener>
		</listeners>
		<vetoListeners>
	        <vetoListener>com.code.aon.account.event.AccountSummaryBeanVetoListener</vetoListener>
		</vetoListeners>
	</bean>

</bean-config>
